### ISSUE TITLE
Secure delivery of predicted document classes

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/SyferText#135]
## Context
When a PySyft classifier is deployed within a SyferText pipeline, and used for inference in SMPC model, on a remote string.

## Problem
The predicted label in this case is a PySyft `AdditiveSharedTensor  (AST)` that only the concerned worker (the data owner) has the right to decrypt, aka, call the `.get()` method on the AST vector.

In order to do this, the output prediction should be sent to the worker, which will decrypt it in turn.

The implies implementing some functionality summarized in the following issue list:

- [ ] [implement `DocPointer.set_predicted_class()`.](https://github.com/OpenMined/SyferText/issues/134)
- [ ] [implement a `SingleLabelClassifier` class](https://github.com/OpenMined/SyferText/issues/136)
- [ ] [Implement a `AverageDocEncoder` class](https://github.com/OpenMined/SyferText/issues/137)

## Where to push your PR?

Any PR referencing this issue should be made to branch `syfertext_0.1.0`

**Comment by bicycleman15** [comment]
This kind off aligns to the project I'm currently doing
